name: Test Help Command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-help:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
    
    - name: Test --help command
      run: |
        python imagenet_helper.py --help
    
    - name: Test subcommand help
      run: |
        python imagenet_helper.py download --help
        python imagenet_helper.py untar --help
        python imagenet_helper.py mds --help
        python imagenet_helper.py status --help